<a href="https://colab.research.google.com/github/Anjani2707/GEN_AI_2303A52419/blob/main/2303A52419_GenAI_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#with out libraries
Yact = [10, 20, 30, 40, 50]
Ypred = [10.2, 20.5, 30.3, 40.8, 50.6]

n = len(Yact)
squared_error = 0
absolute_error = 0

for actual, predicted in zip(Yact, Ypred):
    error = actual - predicted
    squared_error += error ** 2
    absolute_error += abs(error)

mse = squared_error / n
mae = absolute_error / n
rmse = mse ** 0.5

print(f"Mean Squared Error (MSE): {mse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Root Mean Squared Error (RMSE): {rmse}")

Mean Squared Error (MSE): 0.27599999999999947
Mean Absolute Error (MAE): 0.4799999999999997
Root Mean Squared Error (RMSE): 0.5253570214625474


In [ ]:
#with libraries
import numpy as np
Yact = np.array([10, 20, 30, 40, 50])
Ypred = np.array([10.2, 20.5, 30.3, 40.8, 50.6])

mse = np.mean((Yact - Ypred) ** 2)
mae = np.mean(np.abs(Yact - Ypred))
rmse = np.sqrt(mse)

print(f"Mean Squared Error (MSE): {mse}")
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Root Mean Squared Error (RMSE): {rmse}")

Mean Squared Error (MSE): 0.27599999999999947
Mean Absolute Error (MAE): 0.4799999999999997
Root Mean Squared Error (RMSE): 0.5253570214625474


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

# Define the actual and predicted values
Yact = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
Ypredict = [0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 0, 2, 1, 1, 2]

# Compute the confusion matrix
conf_matrix = confusion_matrix(Yact, Ypredict)

# Compute the accuracy
accuracy = accuracy_score(Yact, Ypredict)

# Print the results
print("Confusion Matrix:")
print(conf_matrix)
print("\nAccuracy:")
print(accuracy)


Confusion Matrix:
[[2 2 1]
 [1 3 2]
 [1 2 2]]

Accuracy:
0.4375
